### PR TITLE
Format code automatically with Prettier

### PR DESCRIPTION
**Pull request by staltz**
Like https://github.com/ssb-ngi-pointer/jitdb/pull/32

### CODE REVIEW

**Comment by arj03** [comment]
There is something wierd here. In the jitdb PR it removes space after function so:

from
```
    read(null, function next (err, data) {
```
to

```
    read(null, function next(err, data) {
```

But this does the opposite? Like

  sbot.getVectorClock = function (cb) {

**Comment by staltz** [comment]
When the function is named, it doesn't add a space. When it's anonymous, it adds a name. Just think that there's ways this exact same sequence of chars: `function `

**Comment by arj03** [comment]
So we should name ALL the functions? :)

**Comment by arj03** [comment]
I mean I *really* dislike the space there :-) Everything else is fine. Maybe not such a bad deal because naming function makes debugging easier :thinking:

**Comment by staltz** [comment]
No no ... it's just a formatting style, adds a space in the anonymous case.

**Comment by staltz** [comment]
Yeah, naming functions can be good for debugging (also in production). The code style will turn out to be unsurprising most of the times, and sometimes it will annoy (me or you), but the benefit of this is that we agree to not talk about code style, the machine does it for us, and the core benefit here is avoiding typing. (Nowadays I code sloppy style and let prettier format it for me)

**Comment by arj03** [comment]
Yeah, merging. And now I can always spot when the function is not named, so that maybe a win in the end :-)

**Pull request merged**
