### PR TITLE
refactor: avoid pyramid of ifs and ~ operator

### PR DESCRIPTION
**Pull request by staltz**
Just a cosmetic thing. 

I stumbled upon this while I was thinking about making another level index for abouts such as `{type:'put', key: [content.about, "name"], value: processed}` (might make a PR for that this week, I think it'll be much more efficient than looking for **all** about msgs, what ssb-social-index does)

### CODE REVIEW

**Review by arj03 — APPROVED** [review]

**Comment by arj03** [comment]
social index uses the dest to pick out the right abouts. The browser core actually had a simple level index of author -> latest value for self. Interesting enough loading just this index on startup with ~1000 profiles turned out to take roughly 4 seconds. I do think the heaviest part in all of this is the description, which is why in the latest social index version I only load that when needed (when looking at their profile).

**Comment by arj03** [comment]
One of the reason you might be experiences worse performance is that ssb-suggest uses friends (hops=1) and in the browser I don't have friends (yet, working on it), besides I don't follow that many accounts there. That said it should not be worse than db1.

Another thing is that ssb-suggets does [names](https://github.com/ssbc/ssb-suggest/blob/1d307ece57e84ee3643b684bb4b6463861fd5784/lib/avatar.js#L19) and at least I have no use for that. So I'm thinking of adding a flag to disable that. Do you use that in manyverse?

Another thing that is a bit silly is that there is a cache in ssb-suggest (suggestCache) and then at least I also have a cache for when using about directly. It would be much better with only a single cache.

**Comment by staltz** [comment]
>  I do think the heaviest part in all of this is the description, which is why in the latest social index version I only load that when needed (when looking at their profile).

Interesting, makes sense! 

> had a simple level index of author -> latest value for self

Yeah I was going to do this, but I'm not sure if it's going to be faster than JIT.

> Another thing is that ssb-suggets does names and at least I have no use for that. So I'm thinking of adding a flag to disable that. Do you use that in manyverse?

I don't use that. In fact, I'd much prefer if we just use the person's own self-assigned abouts than the "social value" abouts. It's simpler, faster, and also as a community we haven't had much benefit from social value abouts.

> also have a cache for when using about directly

In Manyverse I use [ssb-cached-about](https://www.npmjs.com/package/ssb-cached-about). I also use ssb-about directly, so I've tested performance in both ways.

**Comment by arj03** [comment]
The thing I found when I was doing the self-assigned name thing was that not everyone has a name then. It seems like some people used they main profile to assign name and pictures to they mobile client.

**Comment by staltz** [comment]
Yeah, I believe that can happen. I'm curious to try only self-assigned names, though, because there will also be a lot of variation in SSB with the patterns of how msgs are authored, hard to "catch all patterns" and it comes with a performance cost too.

**Pull request merged**
