### PR TITLE
add manifest for migrate plugin

### PR DESCRIPTION
**Pull request by staltz**
I needed this in order to call `start()` in Manyverse, new version would be appreciated

### CODE REVIEW

**Comment by arj03** [comment]
I guess with the other fix, this should now be 0.4.0?

**Comment by arj03** [comment]
Or better, include package.version

**Comment by staltz** [comment]
> Or better, include package.version

actually, please not this, `noderify` would end up bundling the whole `package.json` into the final js file, and this time X modules using this pattern is more costly than 1 line of code (that rarely is updated)

**Comment by staltz** [comment]
> I guess with the other fix, this should now be 0.4.0?

when making the commit for `0.4.0` you can also update this line of code in `migrate.js`

**Comment by arj03** [comment]
0.4.0 released

**Pull request merged**
