### PR TITLE
Index rewrite

### PR DESCRIPTION
**Pull request by arj03**
<blank>

### CODE REVIEW

**Comment by staltz** [comment]
Idea: aim to have all secret-stack plugins under a namespace. If the global namespace is unavoidable, put those methods in a dedicated plugin, e.g. `require('ssb-db2/compat')` which defines global namespace methods. Try to have `compat` be a thin wrapper for methods implemented elsewhere.

**Comment by staltz** [comment]
Question: in what module should we call `db2.registerPlugin()`?

**Comment by arj03** [comment]
I would imagine that db2 by default only includes base index. And then you just add a `require('ssb-db2/social')` that would include and register the social indexes. This also allows it to be moved to its own module.

**Comment by arj03** [comment]
node 14 failure seems to be related to ssb-keys 8 using an old version of chloride. See [this](https://github.com/ssb-js/ssb-keys/pull/84#issuecomment-699845253)

**Comment by arj03** [comment]
The node 14 thing just means that it is slow to run the CI. Not a big problem.

**Comment by arj03** [comment]
Reviewed with @staltz

**Pull request merged**
