### PR TITLE
Fix missing config in migrate

### PR DESCRIPTION
**Pull request by arj03**
Found this trying to test this feature.

### CODE REVIEW

**Comment by staltz** [comment]
Oops! Also see https://github.com/ssb-ngi-pointer/ssb-db2/pull/197

**Comment by arj03** [comment]
It is strange that the tests are stalling here, they work fine locally. Will look at #197 quickly, have a call with keks now.

**Comment by staltz** [comment]
> It is strange that the tests are stalling here, they work fine locally.

The `^3.0.4` range for asyncAOL might be automatically installing version 3.0.5

**Comment by staltz** [comment]
If you rebase on master, this might pass tests now.

**Pull request merged**
