### PR TITLE
rework keys index

### PR DESCRIPTION
**Pull request by staltz**
So far this just adds a new benchmark. Will add implementation code later.

### CODE REVIEW

**Comment by staltz** [comment]
@arj03 I pushed the implementation I have so far, and then I'm stopping my work day today. The tests are going to fail (just one), but **if** the benchmarks ran, you'd see a much smaller number for `reboot and key one again`. Maybe you can run it locally if you're curious.

**Comment by arj03** [comment]
Cool thanks. I'm going home now. Will sneak a peak at this tonight though :-)

**Comment by staltz** [comment]
@arj03 This test fails, isn't it supposed to be `t.equal(msg.value.previous, null)`? Because in the previous test, `delete all`, the state of that feed should now be removed from the base index

https://github.com/ssb-ngi-pointer/ssb-db2/blob/5b538159676997de74bc458c655ad145e1310b81/test/basic.js#L188

**Comment by arj03** [comment]
Some numbers from my full db (1.5 mill messages) machine: 6 seconds index create, 92M size.

**Comment by staltz** [comment]
Ouch, 92MB is a lot. I forgot to check that up. Hmm, I wonder if I could do a prefix technique...

**Comment by arj03** [comment]
The keys map prefix index is 34mb in comparison. I can work on updating ssb-friends to the new api, then I can do a better test of performance.

**Comment by arj03** [comment]
This PR decreases the memory usage by 75mb roughly.

**Comment by staltz** [comment]
:arrow_up: Check the benchmark `reboot and key one again`

**Comment by arj03** [comment]
Yeah saw that one locally yesterday as well. It is quite an heavy index to load.

**Comment by staltz** [comment]
Pushed a commit to cut the prefix and suffix in a key. Let's see the benchmarks

**Comment by staltz** [comment]
Lol, basically no change

**Comment by staltz** [comment]
@arj03 We could merge this (for experimentation) or I could install ssb-db2 in Manyverse referencing the `keys-stuff` branch directly. What do you think?

**Comment by arj03** [comment]
Yeah and actually locally here rebuilding the database went from 6s to almost 9. I guess the overhead of creating an extra string is significant.

**Comment by staltz** [comment]
>  went from 6s to almost 9

Wow. Let's see if the CI benchmarks say a similar story too.

**Comment by staltz** [comment]
I'll do this: revert back to full key string, *not merge* this PR (yet), test how it goes in manyverse, and then we can talk about it again.

**Comment by staltz** [comment]
Yeah, tested on mobile, and startup is 3 sec faster (down from 8s to 5s).

Indexes folder looks like this:

```
$ du -h

2.4M	./contacts
1.4M	./aboutSelf
2.6M	./base
4.6M	./fullMentions
17M	./ebt
57M	./keys
```

The original `key__map.32prefixmap` was `21M`.

**Comment by arj03** [comment]
That is good news!

**Comment by staltz** [comment]
Yeah, I checked the old folders on mobile, backlinks takes 262MB, `links` takes 330MB, ssb-threads took 129MB.

The new keys index is not the tiniest, but it's certainly an improvement over db1. Later if we find a smarter way, we can bump the version number for this index. I think this PR would be nice to merge for manyverse, but what's your thoughts on the browser use case?

**Comment by arj03** [comment]
I'll test it later this afternoon and let you know

**Comment by arj03** [comment]
Works great in browser as well. Lets get this merged :-)

**Review by arj03 — APPROVED** [review]

**Pull request merged**
