### PR TITLE
replace mentions leveldb with JITDB includes()

### PR DESCRIPTION
**Pull request by staltz**
### Performance before

```
➜  ssb-db2 git:(master) ✗ rm -rf ~/.ssb/db2/indexes

➜  ssb-db2 git:(master) ✗ node gitignored/example.js    
There are 15 messages
duration: 31616ms

➜  ssb-db2 git:(master) ✗ node gitignored/example.js
There are 15 messages
duration: 475ms

➜  ssb-db2 git:(master) ✗ node gitignored/example.js
There are 15 messages
duration: 469ms

➜  ssb-db2 git:(master) ✗ node gitignored/example.js
There are 15 messages
duration: 465ms
```

### Performance after

```
➜  ssb-db2 git:(includes) ✗ rm -rf ~/.ssb/db2/indexes 

➜  ssb-db2 git:(includes) ✗ node gitignored/example.js
There are 15 messages
duration: 30231ms

➜  ssb-db2 git:(includes) ✗ node gitignored/example.js
There are 15 messages
duration: 435ms

➜  ssb-db2 git:(includes) ✗ node gitignored/example.js
There are 15 messages
duration: 463ms

➜  ssb-db2 git:(includes) ✗ node gitignored/example.js
There are 15 messages
duration: 432ms
```

### `example.js`

```js
const SecretStack = require('secret-stack')
const caps = require('ssb-caps')
const config = require('ssb-config')
const sleep = require('util').promisify(setTimeout)
const { and, isRoot, mentions, channel, toPromise } = require('../operators')

;(async function main() {
  const before = Date.now()
  const sbot = SecretStack({ appKey: caps.shs })
    .use(require('..'))
    .use(require('../migrate'))
    .call(null, config)

  sbot.db.onDrain(async () => {
    const results = await sbot.db.query(
      and(
        mentions('@QlCTpvY7p9ty2yOFrv1WU1AE88aoQc4Y7wYal7PFc+w=.ed25519'),
        isRoot(),
        channel('scuttlebutt')
      ),
      toPromise()
    )
    const after = Date.now()
    const duration = after - before
    console.log('There are ' + results.length + ' messages')
    console.log(`duration: ${duration}ms`)

    sbot.close()
  })
})()

```

### CODE REVIEW

**Comment by staltz** [comment]
Oh, wait, gotta update readme!

**Comment by arj03** [comment]
I think we should leave the mentions index. I still plan on using that in ssb-browser for message links.

**Comment by staltz** [comment]
@arj03 Oh, I didn't know that. Let me find a way of putting it back then, with a slightly different name so people don't get confused which to use.

**Comment by staltz** [comment]
@arj03 How about this now? See the README for a guide

**Comment by arj03** [comment]
Cool, this looks great!

**Pull request merged**
