### PR TITLE
update db.getStatus() to be obv and include jitdb status

### PR DESCRIPTION
**Pull request by staltz**
For issue #139

### CODE REVIEW

**Comment by staltz** [comment]
Performance before: https://github.com/ssb-ngi-pointer/ssb-db2/pull/140#issuecomment-767063797

**Comment by arj03** [comment]
I was wondering why it was so much slower. It must be this line? index.offset((o) => status.updateIndex(index.name, o))

Could you try an % magic number (1000)? :-)

**Comment by staltz** [comment]
I'll try that but I suspect that it's not going to make a big change because index.offset (obv) is already throttled because of the batch and chunkSize system that we made in indexes/plugin.js

**Comment by staltz** [comment]
@arj03 I did

```js

    let i = 0
    index.offset((o) => {
      if (i++ % 1000 === 0) status.updateIndex(index.name, o)
    })
```

And the before and after of performance seems like it hardly gets out of "standard deviation" territory:

```diff
  migration (using ssb-db)
    ✔ delete db2 folder to start clean
    ✔ ssb-db has finished indexing
-   ✔ duration: 3508ms
+   ✔ duration: 2929ms 

  migration (alone)
    ✔ delete db2 folder to start clean
-   ✔ duration: 2952ms
+   ✔ duration: 2749ms

  initial indexing
-   ✔ duration: 1974ms
+   ✔ duration: 2109ms

  initial indexing compat
-   ✔ duration: 371ms
+   ✔ duration: 413ms

  key one initial
-   ✔ duration: 552ms
+   ✔ duration: 504ms

  key two
    ✔ duration: 0ms

  key one again
    ✔ duration: 1ms

  latest root posts
-   ✔ duration: 326ms
+   ✔ duration: 297ms

  latest posts
-   ✔ duration: 24ms
+   ✔ duration: 23ms

  votes one initial
-   ✔ duration: 383ms
+   ✔ duration: 359ms

  votes again
    ✔ duration: 0ms

  hasRoot
-   ✔ duration: 251ms
+   ✔ duration: 260ms

  hasRoot again
    ✔ duration: 0ms

  author one posts
-   ✔ duration: 232ms
+   ✔ duration: 231ms

  author two posts
-   ✔ duration: 54ms
+   ✔ duration: 47ms

  maximum RAM used
    ✔ RAM: 83.37 MB

  total:     20
  passing:   20
  duration:  17s
```

**Comment by arj03** [comment]
Yeah, I'll try rerunning this to see what new number we get.

**Review by arj03 — APPROVED** [review]

**Comment by arj03** [comment]
Quite a bit of variation there. I think this is good.

**Pull request merged**
