### PR TITLE
protect privateIndex.decrypt() from deleted records

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by arj03** [comment]
Seems correct. Would be nice with a test, if for nothing else than make it easy to check how this behaved before. I was wondering if you had a crash in bsb.eq( or bipf.seek before.

**Comment by staltz** [comment]
It was in bipf.seekKey. Let me see if I can make a simple test

**Comment by staltz** [comment]
Updated PR with 1st test :x: 2nd fix :heavy_check_mark:

**Comment by arj03** [comment]
Thanks! Great find :)

**Review by arj03 — APPROVED** [review]

**Pull request merged**
