### PR TITLE
Support sortBy in jitdb

### PR DESCRIPTION
**Pull request by arj03**
This is to support the breaking change in jitdb 5.0

### CODE REVIEW

**Review by staltz — APPROVED** [review]
All good here, but could we make jitdb@6.0.0 with the flumelog error thing updated, and then use that here?

I can make jitdb@6.0.0 if you wish

**Comment by arj03** [comment]
Sure. Go ahead and create jitdb 6 and then update this PR :)

**Comment by arj03** [comment]
I think we can removed that seeing as the only properly tested log is AAOL.

**Comment by staltz** [comment]
@arj03 Final check? I'll let you press merge

**Comment by arj03** [comment]
Great, I can do a release a bit later. 3.1 or 4?

**Comment by staltz** [comment]
New minor, there isn't any breaking change that I can think of

**Pull request merged**
