### PR TITLE
Add self-assigned about index

### PR DESCRIPTION
**Pull request by arj03**
Adds an index for self-assigned about messages.

### CODE REVIEW

**Comment by staltz** [comment]
What was the impact that `description` had on performance (runtime but also storage)?

**Comment by arj03** [comment]
It was actually surprisingly little. Both in terms of indexing performance but also on load. If I remember correctly it took something like 120ms to load this on boot without description and 150ms with description.

**Comment by arj03** [comment]
These tests failures are starting to become problematic. Just restarted it 3-4 times...

**Comment by staltz** [comment]
I recommend we do a `test.skip` for that `config.maxCpu makes indexing last longer` test that is flaky.

**Comment by staltz** [comment]
PR looks good, but do you mind if I work on this branch to add some operator for this? I'd like to have both "get" and live stream APIs for self abouts.

**Comment by arj03** [comment]
Sure, go ahead :)

**Comment by staltz** [comment]
Actually I might do it in a separate PR. So merging :)

**Pull request merged**
