### PR TITLE
move operators from jitdb to ssb-db2

### PR DESCRIPTION
**Pull request by staltz**
To be merged simultaneously with https://github.com/ssb-ngi-pointer/jitdb/pull/27

### CODE REVIEW

**Comment by arj03** [comment]
I really like how this shortens the example code. Feels nice. My only concern is that now query here is different from the one in jitdb, a bit too magical. I know that most people won't use jitdb directly so won't notice, but still. What if instead of:

```
query(
  sbot.db,
  ...
```
it would be: 

```
sbot.db.query(
  ...
```

?

**Comment by staltz** [comment]
@arj03 i'm fine with `sbot.db.query(`

**Comment by arj03** [comment]
Like this right?

**Comment by staltz** [comment]
oooops, I did a git push force and didn't realize you made a commit. i seemed to have deleted your commit, didn't even have time to read it :(

**Comment by arj03** [comment]
Nevermind, they broke the tests ;-)

**Comment by staltz** [comment]
ok both PRs should be in shape now

**Comment by arj03** [comment]
Don't see the sbot.db.query change here?

**Comment by staltz** [comment]
Should be here: https://github.com/ssb-ngi-pointer/ssb-db2/pull/10/files#diff-d7c9c4e37c37bdbf3fd7007e8e5a111ba1cbfecdd20b76f549a385ebc890e552R313 also see tests, it shows `db.query` but that's essentially the same `sbot.db.query`, just the sbot missing

**Comment by arj03** [comment]
I can push the way I saw it to a separate branch, to compare?

**Comment by staltz** [comment]
Yes

**Comment by staltz** [comment]
Oh, the readme isn't updated. That's something that you can feel free to update in this branch or in master if you want. Right now I'm AFK

**Comment by staltz** [comment]
Just to be sure, refresh this page

**Pull request merged**
