### PR TITLE
improve seekers so they always return numbers

### PR DESCRIPTION
**Pull request by staltz**
Similar to https://github.com/ssb-ngi-pointer/jitdb/pull/211

### CODE REVIEW

**Comment by arj03** [comment]
Migration test seems to be failing? test/migration.js:353

**Comment by staltz** [comment]
Yeah I'm looking into it

**Comment by staltz** [comment]
I don't know what was wrong before, but `50` is the correct number, I ran it manually on paper. Maybe this PR made the code behave more correctly and the tests were wrong?

See the comment I added in the tests, inspired by https://github.com/ssb-ngi-pointer/ssb-fixtures/blob/249d6965b8a69f2ed160dba8872a46bced89b386/test/index-feeds.js#L28-L29

**Review by arj03 — APPROVED** [review]
Yeah, great to have these cleaned up

**Pull request merged**
